[package]
name = "trivium"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 2
# rustflags = [ "-C", "no-vectorize-loops", "-C", "no-vectorize-slp" ]

[dependencies]

[dev-dependencies]
expect-test = "1.4.0"
